### ISSUE TITLE
cannot import berserk

### ISSUE THREAD

**Issue by hellipod** [lichess-org/berserk#12]
### Describe the issue

Hello 
Tried to start with (simple examples) in berserk.

Did the pip3 install berserk. During import berserk i get following message:

>>> import berserk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniel/projekte/berserk/berserk.py", line 6, in <module>
    session = berserk.TokenSession(token)
AttributeError: partially initialized module 'berserk' has no attribute 'TokenSession' (most likely due to a circular import)

Regards
Daniel

### Code to reproduce the bug

import berserk

### Berserk version

0.12.2

### Python version

3.10

### Operating system

m1 mac os

**Comment by icp1994** [comment]
Don't name your file `berserk.py`, that's what causing circular imports.

**Comment by hellipod** [comment]
The problem sits in front of the computer!
Thanks a lot! A simple rename of my play-around-file worked. There was something with python file and module names ...
