### ISSUE TITLE
JSON loads encoding error

### ISSUE THREAD

**Issue by AnonJohn** [lichess-org/berserk#15]
Hi - I'm getting this error: TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

For instance: A call to "client.users.get_public_data(u'veysey')" has this traceback below.

I think this stems from the change in Python 3.9 in which the keyword encoding was removed from json.loads

Any advice would be appreciated!

  File "/home/veysey/.local/lib/python3.10/site-packages/berserk/clients.py", line 229, in get_public_data
    return self._r.get(path, converter=models.User.convert)
  File "/home/veysey/.local/lib/python3.10/site-packages/berserk/session.py", line 177, in get
    return self.request(
  File "/home/veysey/.local/lib/python3.10/site-packages/berserk/session.py", line 102, in request
    return fmt.handle(response, is_stream=stream, converter=converter)
  File "/home/veysey/.local/lib/python3.10/site-packages/berserk/formats.py", line 44, in handle
    return converter(self.parse(response))
  File "/home/veysey/.local/lib/python3.10/site-packages/berserk/formats.py", line 87, in parse
    return response.json(cls=self.decoder)
  File "/home/veysey/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/veysey/.local/lib/python3.10/site-packages/simplejson/__init__.py", line 533, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

**Comment by AnonJohn** [comment]
I think this is derivative of a known issue with requests and a multi-year argument over there over whether to default to simplejson or json. Doesn't look like a berzerk issue per se.

https://github.com/psf/requests/issues/4842

**Comment by AnonJohn** [comment]
Discussion of addressing it by catching the error and retrying it in this berserk fork: https://github.com/rhgrant10/berserk/issues/17

**Comment by AnonJohn** [comment]
The change merged in that fork fixes my issue. Not sure if creates other problems. 
https://github.com/ZackClements/berserk/commit/a33272c854ea8ae5b8b53bd2fade31c4ac5857ee

**Comment by AnonJohn** [comment]
To recap this "issue". There is a dispute among requests package maintainers. They use simplejson, which is no longer compatible with the python json library (one has the encoding parameter for "loads", one doesn't). requests maintainers appear unwilling to check for compatibility.

I have simplejson installed; requests uses that preferentially. The ideal solution would be for simplejson and json to require the same arguments. Probably will happen eventually. In the interim requests should test for the library; they have been asked and appear unwilling to fix it.

Thus all upstream users need to test. Options for berserk:
1. Ignore it as an edge case (people impacted can find this thread and make the above fix
2. Consider the patch linked to in the predecessor / pre-fork beserk versions.

Cheers!

**Comment by kraktus** [comment]
Thanks for the report, not sure exactly how to fix at the moment but

> The change merged in that fork fixes my issue. Not sure if creates other problems.
> [ZackClements/berserk@a33272c](https://github.com/ZackClements/berserk/commit/a33272c854ea8ae5b8b53bd2fade31c4ac5857ee)

Is indeed breaking and was quickly reverted afterwards: https://github.com/ZackClements/berserk/pull/5

**Comment by AnonJohn** [comment]
Thanks for the reply. I suggest you simply close the bug; at some point simplejson or requests will surely fix it. Cheers!

**Comment by tors42** [comment]
I heard that uninstalling simplejson might be a workaround as a way to avoid this error.
