### ISSUE TITLE
puzzle activity 404

### ISSUE THREAD

**Issue by AnonJohn** [lichess-org/berserk#16]
Using a personal token with appropriate scopes, calling client.users.get_puzzle_activity() returns a 404 error. The token works for other personal information (e.g. email), so it is generally valid. I recreated several tokens to make sure I had the puzzle activity scope enabled.

 I'm probably doing something wrong, but am stumped. Reporting it in case someone else can verify.

  File "/home/veysey/.local/lib/python3.10/site-packages/berserk/exceptions.py", line 65, in _catch_exception
    response.raise_for_status()
  File "/home/veysey/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/api/user/puzzle-activity

**Comment by kraktus** [comment]
thanks for the report, the endpoint was removed by [5475c272ce7e39e91cba57635b25c3f0e4f72429](https://github.com/lichess-org/lila/commit/5475c272ce7e39e91cba57635b25c3f0e4f72429)

**Comment by kraktus** [comment]
released `v0.12.4` with the fix

**Comment by AnonJohn** [comment]
Many thanks. Confirmed the fix works. Cheers!
