### ISSUE TITLE
`{..., 'pgn': '\n\n\n', ...}` for `client.games.export_ongoing_by_player('...', moves=False, pgn_in_json=True)`

### ISSUE THREAD

**Issue by jacksonthall22** [lichess-org/berserk#19]
Not sure if this is intended behavior or not, or if it's a bug internal to the API.

**Comment by benediktwerner** [comment]
This is simply what the Lichess API returns. It looks like the PGN always ends in 3 newlines. Not sure that's really needed but I don't think it should affect the validity. But you might want to file it on lichess-org/lila.
