### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by yusheng123** [lichess-org/berserk#20]
Hello code owner! Hope you are doing well!

I am trying to contribute to this repo. But I got some problems in setting things up. Could you please have a look?

I finished the GitHub setups, and I am able to:
1.  ssh -T git@github.com
`Hi xyz! You've successfully authenticated, but GitHub does not provide shell access.`
2. created a new branch in another repo on Github

However, I am unable to do that for this repo:
```
$ git checkout -b new_branch   # working and confirmed that I switched to the new branch
$ git push origin new_branch
ERROR: Permission to lichess-org/berserk.git denied to xyz.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

FYI, `git remote -v` shows:
```
origin	git@github.com:lichess-org/berserk.git (fetch)
origin	git@github.com:lichess-org/berserk.git (push)
```

What should I do? Thanks very much!

**Comment by icp1994** [comment]
https://www.dataschool.io/how-to-contribute-on-github/

**Comment by yusheng123** [comment]
Thanks @icp1994 ! It's working now :-)
