### ISSUE TITLE
Add type check in CI 

### ISSUE THREAD

**Issue by kraktus** [lichess-org/berserk#31]
triggered by https://github.com/lichess-org/berserk/pull/30, to ensure type check pass on minimum supported python version.

**Comment by kraktus** [comment]
nevermind it's aiready the case 
https://github.com/lichess-org/berserk/blob/9babbe58cfdf7f6e285d1f1375c66143cde015d1/.github/workflows/test.yml#L39


It's curious the `list` thing of https://github.com/lichess-org/berserk/pull/30, didn't break the test for 3.8 then

**Comment by benediktwerner** [comment]
Ah, we're using `from future import __annotations__` which means annotations won't get evaluated at runtime. Otherwise, `A | B` also wouldn't work, since that's a 3.10 feature. I guess we could switch to `list` and `dict` everywhere then.
