### ISSUE TITLE
Mismatching the details in API docs and actual Response

### ISSUE THREAD

**Issue by shaikhmudassir** [lichess-org/berserk#39]
In the Lichess API documentation, the response schema of [Search teams](https://lichess.org/api#tag/Teams/operation/teamSearch) is mentioned as the [Array of teams](https://github.com/lichess-org/berserk/blob/master/berserk/clients/teams.py#L14). But, it is returning the PaginatedTeams that I have implemented in [this PR](https://github.com/lichess-org/berserk/pull/38/commits/62f0b55655e9e0cbce6ff8f102b3db2c89ee5973) for get_popular_teams(). 

Please take a look at this. I'm implementing the method for search_teams().

**Comment by icp1994** [comment]
The doc is now fixed.

**Comment by shaikhmudassir** [comment]
Thanks @icp1994, I'm moving to development and closing this Issue.
