### ISSUE TITLE
Script that ensure all endpoints are implemented 

### ISSUE THREAD

**Issue by kraktus** [lichess-org/berserk#5]
- From the json of the spec: from https://lichess.org/api or directly from the YAML spec: https://github.com/lichess-org/api/blob/master/doc/specs/lichess-api.yaml extract the list of endpoints (not sure if easier directly from parsing it or using an openAPI reader lib)
- Ensure that every endpoint is covered (a simple grep check that the path is in the code should be enough)
- List endpoints not covered

Optional: implement a rolling GitHub action to run it every week

**Comment by nav-28** [comment]
I took a quick look at this, so I didn't open a pr. Wrote a Python script 
```python
import yaml
import re
with open("lichess-api.yaml") as f:
    spec = yaml.load(f, Loader=yaml.FullLoader)

paths = spec.get('paths', {})
endpoints = []
for endpoint in paths.keys():
    endpoints.append(endpoint)

with open('berserk/clients.py', 'r') as f:
    file_contents = f.read()

missing_endpoints = []
for endpoint in endpoints:
    # Remove leading slash
    endpoint_without_slash = endpoint[1:]

    # Replace parameter placeholders with regular expression
    endpoint_regex = re.sub(r'{[^/]+?}', r'[^/]+?', endpoint_without_slash)
    # Check if endpoint or a variation of it is present in file
    if not re.search(endpoint_regex, file_contents):
        missing_endpoints.append(endpoint)

if missing_endpoints:
    print(f'The following endpoints are not present in the file: {missing_endpoints}')
```

**Comment by benediktwerner** [comment]
Nice, thanks! I made some adjustments and added the script to the repo: https://github.com/lichess-org/berserk/commit/41d62919d103e99ef7ae9c609bedc5aa8497a351
